// Package promrules turns an SLO spec plus a burn-rate policy into a Prometheus
// rule file: one recording rule per distinct window (so alert expressions are
// cheap and dashboards reuse the same series), followed by the multi-window
// multi-burn-rate alerts.
//
// The generated series follow a stable naming scheme so dashboards and queries
// can rely on them:
//
//	slo:sli_error:ratio_rate<window>{slo, service}  – error ratio over <window>
//	slo:error_budget:ratio{slo, service}            – the configured error budget
package promrules

import (
	"fmt"
	"sort"
	"strings"

	"github.com/abhisheksoppanna/slo-autopilot/internal/burnrate"
	"github.com/abhisheksoppanna/slo-autopilot/internal/spec"
	"gopkg.in/yaml.v3"
)

// RuleGroups is the top-level Prometheus rule file structure.
type RuleGroups struct {
	Groups []RuleGroup `yaml:"groups"`
}

// RuleGroup is a named set of rules evaluated together.
type RuleGroup struct {
	Name     string `yaml:"name"`
	Interval string `yaml:"interval,omitempty"`
	Rules    []Rule `yaml:"rules"`
}

// Rule is either a recording rule (Record set) or an alerting rule (Alert set).
type Rule struct {
	Record      string            `yaml:"record,omitempty"`
	Alert       string            `yaml:"alert,omitempty"`
	Expr        string            `yaml:"expr"`
	For         string            `yaml:"for,omitempty"`
	Labels      map[string]string `yaml:"labels,omitempty"`
	Annotations map[string]string `yaml:"annotations,omitempty"`
}

// RecordingRuleName returns the recording-rule metric name for an error ratio
// over the given window, e.g. "slo:sli_error:ratio_rate5m".
func RecordingRuleName(window spec.Duration) string {
	return "slo:sli_error:ratio_rate" + window.Prometheus()
}

// BudgetRuleName is the recording-rule metric exposing the configured budget.
const BudgetRuleName = "slo:error_budget:ratio"

// Generate builds the rule file for a single SLO under the given policy.
func Generate(s spec.SLO, p burnrate.Policy) RuleGroups {
	g := RuleGroup{
		Name:     "slo:" + s.Metadata.Name,
		Interval: "15s",
	}

	commonLabels := baseLabels(s)

	// 1. Error-budget constant, handy for generic dashboard math.
	budgetLabels := cloneLabels(commonLabels)
	g.Rules = append(g.Rules, Rule{
		Record: BudgetRuleName,
		Expr:   fmt.Sprintf("vector(%s)", TrimFloat(s.ErrorBudget())),
		Labels: budgetLabels,
	})

	// 2. One error-ratio recording rule per distinct window.
	for _, w := range p.DistinctWindows() {
		g.Rules = append(g.Rules, Rule{
			Record: RecordingRuleName(w),
			Expr:   ratioExpr(s.Spec.Indicator, w),
			Labels: cloneLabels(commonLabels),
		})
	}

	// 3. Multi-window multi-burn-rate alerts referencing the recording rules.
	budget := s.ErrorBudget()
	base := s.AlertBaseName()
	for _, w := range p.Windows {
		g.Rules = append(g.Rules, alertRule(s, w, base, budget, commonLabels))
	}

	return RuleGroups{Groups: []RuleGroup{g}}
}

// Marshal renders rule groups as a Prometheus-compatible YAML document.
func Marshal(rg RuleGroups) ([]byte, error) {
	out, err := yaml.Marshal(rg)
	if err != nil {
		return nil, fmt.Errorf("marshal rules: %w", err)
	}
	header := "# Generated by slo-autopilot. Do not edit by hand — edit the SLO spec and regenerate.\n"
	return append([]byte(header), out...), nil
}

// ratioExpr delegates to spec.Indicator.RatioExpr so the recording rules, the
// Grafana dashboard, and the live gate all measure the SLI from one definition.
func ratioExpr(ind spec.Indicator, w spec.Duration) string {
	return ind.RatioExpr(w)
}

func alertRule(s spec.SLO, w burnrate.Window, base string, budget float64, common map[string]string) Rule {
	threshold := TrimFloat(w.Factor * budget)
	sel := sloSelector(s)
	expr := fmt.Sprintf(
		"(\n  %s{%s} > %s\n  and\n  %s{%s} > %s\n)",
		RecordingRuleName(w.Long), sel, threshold,
		RecordingRuleName(w.Short), sel, threshold,
	)

	labels := cloneLabels(common)
	labels["severity"] = string(w.Severity)
	labels["burn_window"] = w.Name

	// Impact clause, clamped at 100%: a time-compressed demo policy can have a
	// long window larger than the compliance window, which would otherwise read
	// as a nonsensical ">100% of the budget".
	consumedPct := w.BudgetConsumed(mustWindow(s)) * 100
	impact := fmt.Sprintf("Sustained, this consumes %.0f%% of the budget over %s.", consumedPct, w.Long.Prometheus())
	if consumedPct >= 100 {
		impact = fmt.Sprintf("Sustained, this exhausts the entire error budget within %s.", w.Long.Prometheus())
	}

	return Rule{
		Alert:  base + severitySuffix(w),
		Expr:   expr,
		For:    "2m",
		Labels: labels,
		Annotations: map[string]string{
			"summary": fmt.Sprintf("%s is burning its error budget fast (%gx over %s/%s)",
				s.Metadata.Service, w.Factor, w.Long.Prometheus(), w.Short.Prometheus()),
			"description": fmt.Sprintf(
				"SLO %q (objective %g%% over %s) error ratio exceeds %gx the budget on "+
					"both the %s and %s windows. %s %s",
				s.Metadata.Name, s.Spec.Objective, s.Spec.Window, w.Factor,
				w.Long.Prometheus(), w.Short.Prometheus(), impact, s.Spec.Description,
			),
			"runbook": "https://sre.google/workbook/alerting-on-slos/",
		},
	}
}

func severitySuffix(w burnrate.Window) string {
	// Alert names are <base><Severity><Window>, e.g. …Page1h, …Ticket3d. The
	// window name already makes each alert unique; the severity prefix is there
	// for readability and routing.
	prefix := map[burnrate.Severity]string{
		burnrate.SeverityPage:   "Page",
		burnrate.SeverityTicket: "Ticket",
	}
	return prefix[w.Severity] + upperFirst(w.Name)
}

func sloSelector(s spec.SLO) string {
	return fmt.Sprintf(`slo="%s"`, s.Metadata.Name)
}

func baseLabels(s spec.SLO) map[string]string {
	labels := map[string]string{
		"slo":     s.Metadata.Name,
		"service": s.Metadata.Service,
	}
	if s.Metadata.Team != "" {
		labels["team"] = s.Metadata.Team
	}
	// User labels are copied but never allowed to clobber the structural ones.
	keys := make([]string, 0, len(s.Metadata.Labels))
	for k := range s.Metadata.Labels {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		if _, reserved := labels[k]; !reserved {
			labels[k] = s.Metadata.Labels[k]
		}
	}
	return labels
}

func cloneLabels(in map[string]string) map[string]string {
	out := make(map[string]string, len(in))
	for k, v := range in {
		out[k] = v
	}
	return out
}

func mustWindow(s spec.SLO) spec.Duration {
	d, err := s.WindowDuration()
	if err != nil {
		return 0
	}
	return d
}

// TrimFloat formats a float for embedding in a PromQL expression: no trailing
// zeros, with binary floating-point noise rounded away (1-99.9/100 would
// otherwise render as 0.0009999999999998899 → "0.001"). Shared by the rule and
// dashboard generators so both emit clean thresholds.
func TrimFloat(f float64) string {
	return fmt.Sprintf("%.10g", f)
}

func upperFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
