package promrules

import (
	"strings"
	"testing"

	"github.com/abhisheksoppanna/slo-autopilot/internal/burnrate"
	"github.com/abhisheksoppanna/slo-autopilot/internal/spec"
	"gopkg.in/yaml.v3"
)

func sampleSLO() spec.SLO {
	return spec.SLO{
		APIVersion: spec.APIVersion,
		Metadata: spec.Metadata{
			Name:    "checkout-api-availability",
			Service: "checkout-api",
			Team:    "payments",
		},
		Spec: spec.Spec{
			Description: "Checkout requests succeed.",
			Objective:   99.9,
			Window:      "30d",
			Indicator: spec.Indicator{
				Type:        spec.IndicatorRatio,
				ErrorMetric: `http_requests_total{service="checkout-api",code=~"5.."}`,
				TotalMetric: `http_requests_total{service="checkout-api"}`,
			},
		},
	}
}

func TestGenerateStructure(t *testing.T) {
	s := sampleSLO()
	p := burnrate.Standard()
	rg := Generate(s, p)

	if len(rg.Groups) != 1 {
		t.Fatalf("got %d groups, want 1", len(rg.Groups))
	}
	g := rg.Groups[0]

	var records, alerts int
	for _, r := range g.Rules {
		switch {
		case r.Record != "":
			records++
		case r.Alert != "":
			alerts++
		default:
			t.Errorf("rule is neither record nor alert: %+v", r)
		}
	}

	// 1 budget rule + 1 recording rule per distinct window.
	wantRecords := 1 + len(p.DistinctWindows())
	if records != wantRecords {
		t.Errorf("got %d recording rules, want %d", records, wantRecords)
	}
	// 1 alert per policy window.
	if alerts != len(p.Windows) {
		t.Errorf("got %d alerts, want %d", alerts, len(p.Windows))
	}
}

func TestGenerateThresholds(t *testing.T) {
	s := sampleSLO() // budget = 0.001
	rg := Generate(s, burnrate.Standard())

	// The 1h page alert uses factor 14.4 → threshold 0.0144.
	var found bool
	for _, r := range rg.Groups[0].Rules {
		if r.Alert == "" {
			continue
		}
		if strings.Contains(r.Expr, RecordingRuleName(mustDur(t, "1h"))) && r.Labels["burn_window"] == "1h" {
			found = true
			if !strings.Contains(r.Expr, "0.0144") {
				t.Errorf("1h alert expr missing threshold 0.0144:\n%s", r.Expr)
			}
			if r.Labels["severity"] != "page" {
				t.Errorf("1h alert severity = %q, want page", r.Labels["severity"])
			}
		}
	}
	if !found {
		t.Error("did not find the 1h page alert")
	}
}

func TestAlertNamesUnique(t *testing.T) {
	rg := Generate(sampleSLO(), burnrate.Standard())
	seen := map[string]bool{}
	for _, r := range rg.Groups[0].Rules {
		if r.Alert == "" {
			continue
		}
		if seen[r.Alert] {
			t.Errorf("duplicate alert name %q", r.Alert)
		}
		seen[r.Alert] = true
	}
}

func TestRecordingRuleNamesUnique(t *testing.T) {
	rg := Generate(sampleSLO(), burnrate.Standard())
	seen := map[string]bool{}
	for _, r := range rg.Groups[0].Rules {
		if r.Record == "" {
			continue
		}
		key := r.Record
		if seen[key] {
			t.Errorf("duplicate recording rule %q", key)
		}
		seen[key] = true
	}
}

func TestMarshalIsValidYAML(t *testing.T) {
	rg := Generate(sampleSLO(), burnrate.Standard())
	out, err := Marshal(rg)
	if err != nil {
		t.Fatalf("Marshal: %v", err)
	}
	// Round-trip back through the YAML parser to prove it is well-formed.
	var back RuleGroups
	if err := yaml.Unmarshal(out, &back); err != nil {
		t.Fatalf("generated rules are not valid YAML: %v\n---\n%s", err, out)
	}
	if len(back.Groups) != 1 {
		t.Errorf("round-tripped %d groups, want 1", len(back.Groups))
	}
	if !strings.HasPrefix(string(out), "# Generated by slo-autopilot") {
		t.Error("missing generated-by header comment")
	}
}

func mustDur(t *testing.T, s string) spec.Duration {
	t.Helper()
	d, err := spec.ParseDuration(s)
	if err != nil {
		t.Fatal(err)
	}
	return d
}
